import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.scss';
import { getMdPosts } from '../lib/md-posts';
// import { getJxPosts } from './../lib/jx-posts.js';
import MdPost from '../components/MdPost/MdPost';
import Maintainers from '../components/Project/Maintainers';

const Home: NextPage<{ mdPosts: Array<any> }> = ({ mdPosts }) => {
  // console.log(jxPosts);

  return (
    <div className={styles.container}>
      <Head>
        <title>Hactoberfest &apos;21 - Little Steps</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={'m-0 p-3'}>
        <div className={'p-4'}>
          <h1 className={'text-2xl'}>Hactoberfest 2021 - Little Steps</h1>
        </div>

        <div className={'text-center'}>
          <button
            className={
              'text-center my-4 text-lg bg-green-300 m-auto box-content px-4 py-2 cursor-default text-gray-900 rounded-lg'
            }
          >
            Theme - Climate Change
          </button>
        </div>

        <section>
          <p className={'px-12'}>
            The purpose of this repository is to help the users (developers)
            with Git, GitHub and Open-Source. Besides, this repository is
            designed around Climate-Change. Each post contains some messages on
            climate-change and some steps towards a better tomorrow.
          </p>

          {/* <Maintainers /> */}
        </section>

        <hr className={'m-3'} />

        <section>
          <div>
            <h1 className={'text-xl m-4 mt-6'}>Hackbars: Beginners 🍫</h1>
          </div>

          <div className={'flex flex-row gap-5 flex-wrap justify-center'}>
            {mdPosts.map((post, index) => {
              return <MdPost key={index} post={post} />;
            })}
          </div>
        </section>

        <hr className={'m-3'} />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export const getStaticProps = async () => {
  const mdPosts = await getMdPosts();

  return {
    props: {
      mdPosts: mdPosts.posts,
    },
  };
};

export default Home;
